version: "3"
services:
  postgres:
    container_name: weroad-test-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=weroad-dev

volumes:
  db_data: ~